// Generated by npm run media:variants. Only list files that exist in public/.
export const RESPONSIVE_IMAGE_VARIANTS: Record<string, { src: string; width: number }[]> = {
  "/images/gallery/image10.webp": [
    {
      "src": "/images/gallery/image10-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image10-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image10-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image10-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image11.webp": [
    {
      "src": "/images/gallery/image11-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image11-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image11-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image12.webp": [
    {
      "src": "/images/gallery/image12-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image12-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image12-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image12-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image13.webp": [
    {
      "src": "/images/gallery/image13-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image13-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image13-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image13-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image14.webp": [
    {
      "src": "/images/gallery/image14-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image14-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image14-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image15.webp": [
    {
      "src": "/images/gallery/image15-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image15-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image15-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image15-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image16.webp": [
    {
      "src": "/images/gallery/image16-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image16-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image16-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image17.webp": [
    {
      "src": "/images/gallery/image17-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image17-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image17-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image17-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image19.webp": [
    {
      "src": "/images/gallery/image19-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image19-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image19-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image21.webp": [
    {
      "src": "/images/gallery/image21-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image21-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image21-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image22.webp": [
    {
      "src": "/images/gallery/image22-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image22-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image22-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image24.webp": [
    {
      "src": "/images/gallery/image24-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image24-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image24-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image25.webp": [
    {
      "src": "/images/gallery/image25-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image25-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image25-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image36.webp": [
    {
      "src": "/images/gallery/image36-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image36-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image36-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image36-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image37.webp": [
    {
      "src": "/images/gallery/image37-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image37-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image37-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image37-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image38.webp": [
    {
      "src": "/images/gallery/image38-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image38-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image38-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image38-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image39.webp": [
    {
      "src": "/images/gallery/image39-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image39-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image39-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image39-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image40.webp": [
    {
      "src": "/images/gallery/image40-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image40-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image40-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image41.webp": [
    {
      "src": "/images/gallery/image41-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image41-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image41-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image42.webp": [
    {
      "src": "/images/gallery/image42-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image42-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image42-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image42-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image43.webp": [
    {
      "src": "/images/gallery/image43-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image43-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image43-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image43-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image44.webp": [
    {
      "src": "/images/gallery/image44-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image44-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image44-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image44-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image45.webp": [
    {
      "src": "/images/gallery/image45-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image45-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image45-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image45-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image46.webp": [
    {
      "src": "/images/gallery/image46-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image46-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image46-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image46-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image47.webp": [
    {
      "src": "/images/gallery/image47-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image47-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image47-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image47-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image48.webp": [
    {
      "src": "/images/gallery/image48-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image48-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image48-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image48-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image49.webp": [
    {
      "src": "/images/gallery/image49-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image49-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image49-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image50.webp": [
    {
      "src": "/images/gallery/image50-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image50-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image50-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image51.webp": [
    {
      "src": "/images/gallery/image51-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image51-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image51-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image51-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image52.webp": [
    {
      "src": "/images/gallery/image52-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image52-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image52-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image52-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image53.webp": [
    {
      "src": "/images/gallery/image53-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image53-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image53-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image54.webp": [
    {
      "src": "/images/gallery/image54-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image54-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image54-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image54-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image55.webp": [
    {
      "src": "/images/gallery/image55-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image55-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image55-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image56.webp": [
    {
      "src": "/images/gallery/image56-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image56-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image56-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image56-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image57.webp": [
    {
      "src": "/images/gallery/image57-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image57-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image57-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image57-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image58.webp": [
    {
      "src": "/images/gallery/image58-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image58-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image58-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image58-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image59.webp": [
    {
      "src": "/images/gallery/image59-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image59-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image59-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image59-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image60.webp": [
    {
      "src": "/images/gallery/image60-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image60-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image60-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image60-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image61.webp": [
    {
      "src": "/images/gallery/image61-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image61-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image61-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image62.webp": [
    {
      "src": "/images/gallery/image62-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image62-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image62-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image62-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image63.webp": [
    {
      "src": "/images/gallery/image63-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image63-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image63-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image63-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image64.webp": [
    {
      "src": "/images/gallery/image64-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image64-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image64-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image64-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image65.webp": [
    {
      "src": "/images/gallery/image65-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image65-800w.webp",
      "width": 800
    }
  ],
  "/images/gallery/image68.webp": [
    {
      "src": "/images/gallery/image68-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image68-800w.webp",
      "width": 800
    }
  ],
  "/images/gallery/image70.webp": [
    {
      "src": "/images/gallery/image70-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image70-800w.webp",
      "width": 800
    }
  ],
  "/images/gallery/image72.webp": [
    {
      "src": "/images/gallery/image72-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image72-800w.webp",
      "width": 800
    }
  ],
  "/images/services/alaga-iduro.webp": [
    {
      "src": "/images/services/alaga-iduro-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/alaga-iduro-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/alaga-iduro-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/alaga-iduro-1600w.webp",
      "width": 1600
    }
  ],
  "/images/services/alaga-ijoko.webp": [
    {
      "src": "/images/services/alaga-ijoko-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/alaga-ijoko-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/alaga-ijoko-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/alaga-ijoko-1600w.webp",
      "width": 1600
    }
  ],
  "/images/services/engagement-cordination.webp": [
    {
      "src": "/images/services/engagement-cordination-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/engagement-cordination-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/engagement-cordination-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/engagement-cordination-1600w.webp",
      "width": 1600
    }
  ],
  "/images/services/eru-iyawo.webp": [
    {
      "src": "/images/services/eru-iyawo-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/eru-iyawo-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/eru-iyawo-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/eru-iyawo-1600w.webp",
      "width": 1600
    }
  ],
  "/assets/hero/hero1.webp": [
    {
      "src": "/assets/hero/hero1-400w.webp",
      "width": 400
    },
    {
      "src": "/assets/hero/hero1-800w.webp",
      "width": 800
    },
    {
      "src": "/assets/hero/hero1-1200w.webp",
      "width": 1200
    },
    {
      "src": "/assets/hero/hero1-1600w.webp",
      "width": 1600
    }
  ],
  "/assets/hero/hero2.webp": [
    {
      "src": "/assets/hero/hero2-400w.webp",
      "width": 400
    },
    {
      "src": "/assets/hero/hero2-800w.webp",
      "width": 800
    },
    {
      "src": "/assets/hero/hero2-1200w.webp",
      "width": 1200
    },
    {
      "src": "/assets/hero/hero2-1600w.webp",
      "width": 1600
    }
  ]
};
