// Generated by npm run media:variants. Only list files that exist in public/.
export const RESPONSIVE_IMAGE_VARIANTS: Record<string, { src: string; width: number }[]> = {
  "/images/gallery/image10.webp.jpeg": [
    {
      "src": "/images/gallery/image10.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image10.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image10.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image10.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image11.webp.jpeg": [
    {
      "src": "/images/gallery/image11.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image11.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image11.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image12.webp.jpeg": [
    {
      "src": "/images/gallery/image12.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image12.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image12.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image12.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image13.webp.jpeg": [
    {
      "src": "/images/gallery/image13.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image13.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image13.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image13.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image14.webp.jpeg": [
    {
      "src": "/images/gallery/image14.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image14.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image14.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image15.webp.jpeg": [
    {
      "src": "/images/gallery/image15.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image15.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image15.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image15.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image16.webp.jpeg": [
    {
      "src": "/images/gallery/image16.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image16.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image16.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image17.webp.jpeg": [
    {
      "src": "/images/gallery/image17.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image17.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image17.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image17.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image19.webp.jpeg": [
    {
      "src": "/images/gallery/image19.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image19.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image19.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image21.webp.jpeg": [
    {
      "src": "/images/gallery/image21.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image21.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image21.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image22.webp.jpeg": [
    {
      "src": "/images/gallery/image22.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image22.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image22.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image24.webp.jpeg": [
    {
      "src": "/images/gallery/image24.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image24.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image24.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image25.webp.jpeg": [
    {
      "src": "/images/gallery/image25.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image25.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image25.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image36.webp.jpeg": [
    {
      "src": "/images/gallery/image36.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image36.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image36.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image36.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image37.webp.jpeg": [
    {
      "src": "/images/gallery/image37.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image37.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image37.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image37.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image38.webp.jpeg": [
    {
      "src": "/images/gallery/image38.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image38.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image38.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image38.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image39.webp.jpeg": [
    {
      "src": "/images/gallery/image39.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image39.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image39.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image39.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image40.webp.jpeg": [
    {
      "src": "/images/gallery/image40.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image40.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image40.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image41.webp.jpeg": [
    {
      "src": "/images/gallery/image41.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image41.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image41.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image42.webp.jpeg": [
    {
      "src": "/images/gallery/image42.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image42.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image42.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image42.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image43.webp.jpeg": [
    {
      "src": "/images/gallery/image43.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image43.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image43.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image43.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image44.webp.jpeg": [
    {
      "src": "/images/gallery/image44.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image44.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image44.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image44.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image45.webp.jpeg": [
    {
      "src": "/images/gallery/image45.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image45.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image45.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image45.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image46.webp.jpeg": [
    {
      "src": "/images/gallery/image46.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image46.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image46.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image46.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image47.webp.jpeg": [
    {
      "src": "/images/gallery/image47.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image47.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image47.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image47.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image48.webp.jpeg": [
    {
      "src": "/images/gallery/image48.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image48.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image48.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image48.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image49.webp.jpeg": [
    {
      "src": "/images/gallery/image49.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image49.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image49.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image50.webp.jpeg": [
    {
      "src": "/images/gallery/image50.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image50.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image50.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image51.webp.jpeg": [
    {
      "src": "/images/gallery/image51.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image51.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image51.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image51.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image52.webp.jpeg": [
    {
      "src": "/images/gallery/image52.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image52.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image52.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image52.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image53.webp.jpeg": [
    {
      "src": "/images/gallery/image53.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image53.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image53.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image54.webp.jpeg": [
    {
      "src": "/images/gallery/image54.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image54.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image54.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image54.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image55.webp.jpeg": [
    {
      "src": "/images/gallery/image55.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image55.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image55.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image56.webp.jpeg": [
    {
      "src": "/images/gallery/image56.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image56.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image56.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image56.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image57.webp.jpeg": [
    {
      "src": "/images/gallery/image57.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image57.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image57.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image57.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image58.webp.jpeg": [
    {
      "src": "/images/gallery/image58.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image58.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image58.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image58.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image59.webp.jpeg": [
    {
      "src": "/images/gallery/image59.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image59.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image59.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image59.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image60.webp.jpeg": [
    {
      "src": "/images/gallery/image60.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image60.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image60.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image60.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image61.webp.jpeg": [
    {
      "src": "/images/gallery/image61.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image61.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image61.webp-1200w.webp",
      "width": 1200
    }
  ],
  "/images/gallery/image62.webp.jpeg": [
    {
      "src": "/images/gallery/image62.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image62.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image62.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image62.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image63.webp.jpeg": [
    {
      "src": "/images/gallery/image63.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image63.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image63.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image63.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image64.webp.jpeg": [
    {
      "src": "/images/gallery/image64.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image64.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/gallery/image64.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/gallery/image64.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/gallery/image65.webp.jpeg": [
    {
      "src": "/images/gallery/image65.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image65.webp-800w.webp",
      "width": 800
    }
  ],
  "/images/gallery/image68.webp.jpeg": [
    {
      "src": "/images/gallery/image68.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image68.webp-800w.webp",
      "width": 800
    }
  ],
  "/images/gallery/image70.webp.jpeg": [
    {
      "src": "/images/gallery/image70.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image70.webp-800w.webp",
      "width": 800
    }
  ],
  "/images/gallery/image72.webp.jpeg": [
    {
      "src": "/images/gallery/image72.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/gallery/image72.webp-800w.webp",
      "width": 800
    }
  ],
  "/images/services/alaga-iduro.webp": [
    {
      "src": "/images/services/alaga-iduro-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/alaga-iduro-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/alaga-iduro-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/alaga-iduro-1600w.webp",
      "width": 1600
    }
  ],
  "/images/services/alaga-ijoko.webp.jpeg": [
    {
      "src": "/images/services/alaga-ijoko.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/alaga-ijoko.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/alaga-ijoko.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/alaga-ijoko.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/services/engagement-cordination.webp.jpeg": [
    {
      "src": "/images/services/engagement-cordination.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/engagement-cordination.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/engagement-cordination.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/engagement-cordination.webp-1600w.webp",
      "width": 1600
    }
  ],
  "/images/services/eru-iyawo.webp.jpeg": [
    {
      "src": "/images/services/eru-iyawo.webp-400w.webp",
      "width": 400
    },
    {
      "src": "/images/services/eru-iyawo.webp-800w.webp",
      "width": 800
    },
    {
      "src": "/images/services/eru-iyawo.webp-1200w.webp",
      "width": 1200
    },
    {
      "src": "/images/services/eru-iyawo.webp-1600w.webp",
      "width": 1600
    }
  ]
};
