import React from 'react';
import { Container } from '../components/Container';
import { PageHero } from '../components/PageHero';
import { SEO } from '../components/SEO';

const heading = 'font-display text-2xl font-normal text-burgundy-deep sm:text-3xl';
const text = 'leading-relaxed text-charcoal-soft/85';

export const AccessibilityStatementShell: React.FC = () => (
  <>
    <SEO title="Accessibility Statement | D’Fabulous Events" description="D’Fabulous Events’ accessibility objectives, known limitations and contact route for reporting accessibility problems." />
    <PageHero title="Accessibility Statement" subtitle="Our continuing work to make the D’Fabulous website easier to use for everyone." breadcrumbs={[{ label: 'Home', href: '/' }, { label: 'Accessibility' }]} />
    <main className="bg-ivory-warm py-16 text-charcoal-soft sm:py-24"><Container><article className="mx-auto max-w-4xl space-y-12">
      <header className="border-b border-burgundy-deep/15 pb-8"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold-dark">Last updated: 2 September 2026</p><p className="mt-5 max-w-3xl text-lg leading-relaxed text-charcoal-soft/90">D’Fabulous Luxury Yoruba Events aims to provide an accessible, welcoming website for couples, families, planners and guests exploring Yoruba cultural event services.</p></header>
      <section className="space-y-4"><h2 className={heading}>1. Our Accessibility Objective</h2><p className={text}>We aim to meet WCAG 2.2 AA principles of perceivable, operable, understandable and robust content. This is an ongoing objective, not a claim that every part of the website currently meets every success criterion.</p></section>
      <section className="space-y-4"><h2 className={heading}>2. Current Accessibility Features</h2><ul className="list-disc space-y-2 pl-5 leading-relaxed text-charcoal-soft/85"><li>semantic headings, landmarks and labelled navigation;</li><li>keyboard-accessible links, buttons, menus and form controls;</li><li>visible focus states for interactive controls;</li><li>skip navigation support;</li><li>responsive layouts for mobile, tablet and desktop screens;</li><li>alternative text on meaningful images where provided; and</li><li>readable colour, spacing and typography within the existing D’Fabulous design system.</li></ul></section>
      <section className="space-y-4"><h2 className={heading}>3. Keyboard and Screen Reader Use</h2><p className={text}>The website is designed so core navigation, service information, booking enquiries and contact forms can be reached with a keyboard. Labels, headings, status messages and error descriptions are provided where practical for assistive technology. Compatibility can vary by browser, device and assistive technology combination.</p></section>
      <section className="space-y-4"><h2 className={heading}>4. Images, Colour and Readability</h2><p className={text}>We provide alternative text for meaningful imagery and aim to maintain sufficient contrast, readable text sizes and clear focus indicators. Decorative imagery is not intended to carry essential information. Some photography, video, animated content or brand styling may not be fully accessible to every visitor.</p></section>
      <section className="space-y-4"><h2 className={heading}>5. Mobile and Responsive Accessibility</h2><p className={text}>The website adapts to smaller screens and touch interaction. Visitors may still experience limitations caused by device settings, zoom, browser behaviour, large media, fixed interface elements or third-party operating-system features.</p></section>
      <section className="space-y-4"><h2 className={heading}>6. Known Limitations</h2><p className={text}>The website has not been certified as fully WCAG 2.2 AA compliant. Known or possible limitations include the accessibility of some video content, complex visual galleries, third-party social-media destinations, external WhatsApp content, and content supplied or changed through external services. We review reported issues and prioritise improvements according to impact.</p></section>
      <section className="space-y-4"><h2 className={heading}>7. Third-Party Content</h2><p className={text}>Links to WhatsApp, Facebook, Instagram and TikTok lead to independent services. D’Fabulous does not control their accessibility, user interface or assistive-technology compatibility. Those providers may offer their own accessibility and support information.</p></section>
      <section className="space-y-4"><h2 className={heading}>8. Report an Accessibility Problem</h2><p className={text}>Tell us what you were trying to do, the page or feature involved, the device and browser used, and the nature of the difficulty. Do not include passwords or unnecessary sensitive information. Contact <a className="font-medium text-burgundy-rich underline underline-offset-4" href="mailto:fabulousevents@hotmail.com">fabulousevents@hotmail.com</a> or use the official WhatsApp contact displayed on the website.</p></section>
      <section className="space-y-4"><h2 className={heading}>9. Review and Updates</h2><p className={text}>D’Fabulous will review this statement when the website, content, services or accessibility expectations change and will record material updates through a revised date. We may ask for further information to reproduce and address a reported issue.</p></section>
      <section className="border-t border-burgundy-deep/15 pt-10 space-y-4"><h2 className={heading}>10. Contact Details</h2><address className="not-italic leading-relaxed text-burgundy-deep"><strong>DFABULOUSS ENT LTD</strong><br />Trading as D’Fabulous Luxury Yoruba Events / D’Fabulous Events<br />Company Registration No. 12638479<br />VAT registered: No<br /><br />7 Bell Yard<br />London WC2A 2JR<br />United Kingdom<br /><br />Email: <a className="underline underline-offset-4" href="mailto:fabulousevents@hotmail.com">fabulousevents@hotmail.com</a><br />Contact method: Email and WhatsApp</address></section>
    </article></Container></main>
  </>
);