import React from 'react';
import { Container } from '../components/Container';
import { PageHero } from '../components/PageHero';
import { SEO } from '../components/SEO';

const heading = 'font-display text-2xl font-normal text-burgundy-deep sm:text-3xl';
const text = 'leading-relaxed text-charcoal-soft/85';

export const BookingTermsShell: React.FC = () => (
  <>
    <SEO title="Booking Terms & Conditions | D’Fabulous Events" description="Booking terms for D’Fabulous Luxury Yoruba Events, including deposits, payment schedules, cancellations and event responsibilities." />
    <PageHero title="Booking Terms & Conditions" subtitle="The practical terms for reserving D’Fabulous event services." breadcrumbs={[{ label: 'Home', href: '/' }, { label: 'Booking Terms' }]} />
    <main className="bg-ivory-warm py-16 text-charcoal-soft sm:py-24"><Container><article className="mx-auto max-w-4xl space-y-12">
      <header className="border-b border-burgundy-deep/15 pb-8"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold-dark">Last updated: 2 September 2026</p><p className="mt-5 max-w-3xl text-lg leading-relaxed text-charcoal-soft/90">These Booking Terms apply to event services supplied by DFABULOUSS ENT LTD, trading as D’Fabulous Luxury Yoruba Events and D’Fabulous Events. They should be read with the client’s quotation, booking confirmation, invoice and any event-specific written agreement.</p></header>
      <section className="space-y-4"><h2 className={heading}>1. Enquiry and Availability</h2><p className={text}>An enquiry or booking form does not create a confirmed booking. Availability is checked against the requested date, venue, service scope, travel requirements and supplier availability. D’Fabulous may continue to consider other enquiries until the booking is confirmed.</p></section>
      <section className="space-y-4"><h2 className={heading}>2. Quote Validity</h2><p className={text}>A quotation describes the proposed services, price and assumptions at the time it is issued. Its validity period, if any, will be stated in the quotation. A quotation may change if the client changes the date, venue, guest numbers, services, timings, travel or third-party requirements before acceptance.</p></section>
      <section className="space-y-4"><h2 className={heading}>3. Booking Confirmation</h2><p className={text}>A booking is confirmed only when D’Fabulous has formally accepted it and the required payment has been received and cleared. A confirmed booking may be assigned a booking reference, which should be used in communications about the event.</p></section>
      <section className="space-y-4"><h2 className={heading}>4. Deposit and Date Lock-In</h2><p className={text}>D’Fabulous may require a minimum deposit of 30% of the actual booking amount to secure the date. A different amount may be agreed in writing. The booking amount is not fixed at £5,000; it is the amount quoted and accepted for the services. The date is not locked in until the booking is accepted and the required deposit has cleared. Amounts already paid are credited against the total.</p></section>
      <section className="space-y-4"><h2 className={heading}>5. Payment Schedule and Balance</h2><p className={text}>The booking confirmation or invoice will state the total agreed amount, payments received, deposit requirement and outstanding balance where applicable. The remaining balance must be paid by the deadline communicated in those booking documents. No universal deadline is imposed by these general terms.</p></section>
      <section className="space-y-4"><h2 className={heading}>6. Late Payments</h2><p className={text}>If a payment is late, D’Fabulous may pause preparation, request payment, or decline an unconfirmed date where permitted by the agreement and law. It will consider the circumstances and will not remove mandatory consumer rights.</p></section>
      <section className="space-y-4"><h2 className={heading}>7. Changes and Additional Services</h2><p className={text}>Changes to the event date, location, duration, guest numbers, timings, programme or requirements may affect availability, supplier commitments and price. Additional services or work will be confirmed in writing with any additional charge before being treated as agreed.</p></section>
      <section className="space-y-4"><h2 className={heading}>8. Client Responsibilities</h2><p className={text}>The client must provide accurate event information, timely decisions and approvals, safe access, suitable working conditions and any permissions or licences within the client’s responsibility. The client must tell D’Fabulous about accessibility needs, hazards, venue rules and material changes as early as possible.</p></section>
      <section className="space-y-4"><h2 className={heading}>9. Venue, Timings and Access</h2><p className={text}>The client is responsible for arranging venue access, loading, parking, facilities, permissions and agreed timings. Delayed access, late starts or venue restrictions may affect delivery and may create reasonable additional costs where permitted by the booking agreement.</p></section>
      <section className="space-y-4"><h2 className={heading}>10. Suppliers and Third Parties</h2><p className={text}>D’Fabulous may coordinate independent suppliers or subcontractors for décor, entertainment, production, travel, venue-related or other agreed elements. Supplier availability, terms and costs may affect the booking. D’Fabulous will remain responsible for the services it has agreed to provide, subject to applicable law.</p></section>
      <section className="space-y-4"><h2 className={heading}>11. Delays and Force Majeure</h2><p className={text}>D’Fabulous will take reasonable steps to deliver at the agreed time, but event timings can be affected by venues, guests, suppliers, traffic or circumstances outside its control. Force majeure includes events such as extreme weather, natural disaster, serious public emergency, government restriction, war, terrorism, civil unrest, major transport disruption or supplier failure outside reasonable control. It does not include ordinary poor planning or avoidable business problems.</p></section>
      <section className="space-y-4"><h2 className={heading}>12. Cancellation and Rescheduling</h2><p className={text}>Client cancellations, D’Fabulous cancellation, postponement, supplier costs and rescheduling are governed by the separate <a className="font-medium text-burgundy-rich underline underline-offset-4" href="/cancellation-refund-rescheduling">Cancellation, Refund & Rescheduling Policy</a>. Rescheduling depends on D’Fabulous, supplier and venue availability and is not automatically guaranteed.</p></section>
      <section className="space-y-4"><h2 className={heading}>13. Refunds</h2><p className={text}>Refunds are assessed by reference to payments made, services and preparation completed, cancellation timing, supplier commitments and genuine non-recoverable costs, subject to applicable law. Deposits are not automatically non-refundable in every circumstance.</p></section>
      <section className="space-y-4"><h2 className={heading}>14. Event Conduct and Safety</h2><p className={text}>The client is responsible for reasonable guest behaviour, venue rules, alcohol arrangements, catering, food safety, security and third-party services outside D’Fabulous’s agreed scope. D’Fabulous may pause or withdraw from an unsafe situation, subject to its legal responsibilities.</p></section>
      <section className="space-y-4"><h2 className={heading}>15. Property and Damage</h2><p className={text}>The client is responsible for damage caused by the client or guests to D’Fabulous or supplier property, except where the relevant provider is legally responsible. Personal belongings remain the owner’s responsibility unless applicable law provides otherwise.</p></section>
      <section className="space-y-4"><h2 className={heading}>16. Media and Intellectual Property</h2><p className={text}>Photography or video supplied as part of a booking will be governed by the agreed service scope. D’Fabulous will seek appropriate permission or another lawful basis before using identifiable client images for promotion. D’Fabulous retains rights in its brand, original concepts, schedules, methods and materials unless agreed otherwise.</p></section>
      <section className="space-y-4"><h2 className={heading}>17. Consumer Rights and Liability</h2><p className={text}>Nothing in these Booking Terms excludes or limits rights or liability that cannot legally be excluded, including applicable protections under the Consumer Rights Act 2015. D’Fabulous is responsible for losses reasonably foreseeable and caused by its breach, subject to applicable law. No term requires a consumer to waive statutory rights.</p></section>
      <section className="space-y-4"><h2 className={heading}>18. Complaints</h2><p className={text}>Raise concerns promptly so D’Fabulous can review the booking records and circumstances. Contact <a className="font-medium text-burgundy-rich underline underline-offset-4" href="mailto:fabulousevents@hotmail.com">fabulousevents@hotmail.com</a> or use the official WhatsApp contact displayed on the website. This process does not remove the right to pursue a legal remedy.</p></section>
      <section className="space-y-4"><h2 className={heading}>19. Governing Law</h2><p className={text}>These Booking Terms are governed by the laws of England and Wales, subject to mandatory consumer protection laws applicable to the client.</p></section>
      <section className="border-t border-burgundy-deep/15 pt-10 space-y-4"><h2 className={heading}>20. Contact</h2><address className="not-italic leading-relaxed text-burgundy-deep"><strong>DFABULOUSS ENT LTD</strong><br />D’Fabulous Luxury Yoruba Events / D’Fabulous Events<br />Company Registration No. 12638479<br />VAT registered: No<br /><br />7 Bell Yard<br />London WC2A 2JR<br />United Kingdom<br /><br />Email: <a className="underline underline-offset-4" href="mailto:fabulousevents@hotmail.com">fabulousevents@hotmail.com</a><br />Primary customer communication: WhatsApp and email</address></section>
    </article></Container></main>
  </>
);