import React from 'react';
import { Container } from '../components/Container';
import { PageHero } from '../components/PageHero';
import { SEO } from '../components/SEO';

const heading = 'font-display text-2xl font-normal text-burgundy-deep sm:text-3xl';
const text = 'leading-relaxed text-charcoal-soft/85';

const auditInventory = [
  ['Google Fonts stylesheet and font files', 'Google', 'Loads Cormorant Garamond and Plus Jakarta Sans for the website typography.', 'Third-party resource; not a cookie', 'Not specified by provider', 'Third-party', 'No cookie observed; PECR cookie consent is not asserted for this request'],
  ['Supabase JavaScript client and REST requests', 'Supabase', 'Retrieves public website content and provides authentication capability for administration.', 'Application service; not a cookie', 'Request/session behaviour varies; no anonymous storage key observed', 'Third-party service', 'No cookie observed on anonymous first load'],
  ['D’Fabulous application API requests', 'D’Fabulous website', 'Supports gallery, testimonial, booking and contact workflows through server routes.', 'First-party application request; not a cookie', 'Request duration', 'First-party', 'No cookie observed on anonymous first load'],
  ['External social links', 'WhatsApp, Facebook, Instagram and TikTok', 'Takes a visitor to an independent service when the visitor chooses to follow a link.', 'Third-party link; not an embedded tracker', 'Until the visitor leaves the website', 'Third-party after navigation', 'No third-party cookie observed before navigation'],
];

export const CookiePolicyShell: React.FC = () => (
  <>
    <SEO title="Cookie Policy | D’Fabulous Events" description="How DFABULOUSS ENT LTD, trading as D’Fabulous Events, uses cookies and similar technologies." />
    <PageHero title="Cookie Policy" subtitle="An accurate account of cookies, browser storage and third-party requests on the D’Fabulous Events website." breadcrumbs={[{ label: 'Home', href: '/' }, { label: 'Cookie Policy' }]} />
    <main className="bg-ivory-warm py-16 text-charcoal-soft sm:py-24">
      <Container>
        <article className="mx-auto max-w-4xl space-y-12">
          <header className="border-b border-burgundy-deep/15 pb-8"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold-dark">Effective date: 2 September 2026</p><p className="mt-2 text-xs font-semibold uppercase tracking-[0.22em] text-gold-dark">Last updated: 2 September 2026</p><p className="mt-5 max-w-3xl text-lg leading-relaxed text-charcoal-soft/90">This Cookie Policy explains what the D’Fabulous Events website currently uses, what the audit did not find, and how cookies or similar technologies will be handled if the website changes.</p></header>

          <section className="space-y-4"><h2 className={heading}>1. Introduction</h2><p className={text}>Cookies can help a website remember a browser, support a requested function or measure use. Similar technologies include browser storage, pixels, tags and scripts. This policy reflects an inspection of the current public source code, configuration, dependencies and an anonymous first-load browser request and storage check.</p></section>
          <section className="space-y-4"><h2 className={heading}>2. About D’Fabulous Events</h2><p className={text}>The website is operated by DFABULOUSS ENT LTD, trading as D’Fabulous Luxury Yoruba Events and D’Fabulous Events. D’Fabulous provides Yoruba ceremonial hosting, event-service information, booking enquiries and related event services.</p><address className="border-l-2 border-gold-luxury pl-5 not-italic leading-relaxed text-burgundy-deep"><strong>DFABULOUSS ENT LTD</strong><br />7 Bell Yard<br />London WC2A 2JR<br />United Kingdom<br />Company number: 12638479<br />VAT: Not VAT registered / N/A<br />Email: <a className="underline underline-offset-4" href="mailto:fabulousevents@hotmail.com">fabulousevents@hotmail.com</a></address></section>
          <section className="space-y-4"><h2 className={heading}>3. What Cookies Are</h2><p className={text}>A cookie is a small text file stored on a visitor’s device by a website. Session cookies normally expire when the browser session ends; persistent cookies remain for a period set by their provider or until deleted. Online identifiers and other stored information may be personal data depending on the circumstances.</p></section>
          <section className="space-y-4"><h2 className={heading}>4. How D’Fabulous Uses Cookies and Similar Technologies</h2><p className={text}>The website supports navigation, event-service information, booking and contact forms, availability requests, application API requests, and WhatsApp or email contact. Its code may use technical mechanisms for those functions, security and protection against automated form submissions. The audit found no named browser cookie being set for these functions.</p><p className={text}>The website loads its chosen fonts from Google Fonts and requests public content through its application and Supabase services. Those are external resource or application requests, not automatically cookies.</p></section>
          <section className="space-y-5"><h2 className={heading}>5. Types of Cookies Used</h2><p className={text}>The categories below explain the distinction but do not assert that every category is active.</p><div className="overflow-x-auto border border-burgundy-deep/15"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><caption className="sr-only">Cookie categories, purposes and consent status</caption><thead className="bg-burgundy-deep text-xs uppercase tracking-wider text-ivory-warm"><tr><th className="p-4">Category</th><th className="p-4">What it may do</th><th className="p-4">Current status and consent</th></tr></thead><tbody>{[['Strictly necessary cookies','Support website operation, security or a service requested by a visitor.','No named cookie verified. Consent may not be required only where strictly necessary.'],['Functional/preference cookies','Remember a preference or optional convenience.','No named preference cookie or storage key verified. Optional use requires consent where applicable.'],['Analytics cookies','Measure visits, page use, performance or errors.','No analytics tool or cookie verified. No consent mechanism currently exists.'],['Marketing/advertising cookies','Measure or personalise advertising across services.','No marketing pixel, tag or cookie verified. No consent mechanism currently exists.'],['Third-party cookies','Are placed by an integrated external provider.','No embedded third-party cookie service verified on page load. Any future integration requires review.']].map(([category, purpose, status]) => <tr key={category} className="border-t border-burgundy-deep/15 align-top"><th scope="row" className="p-4 font-semibold text-burgundy-deep">{category}</th><td className="p-4 leading-relaxed">{purpose}</td><td className="p-4 leading-relaxed">{status}</td></tr>)}</tbody></table></div></section>
          <section className="space-y-5"><h2 className={heading}>6. Verified Technology Inventory</h2><p className={text}>The following table contains the technologies identified by the audit. These entries are not cookie names. No named cookie was found, so none is invented here.</p><div className="overflow-x-auto border border-burgundy-deep/15"><table className="w-full min-w-[1050px] border-collapse text-left text-sm"><caption className="sr-only">Audited technologies used by the D’Fabulous website</caption><thead className="bg-burgundy-deep text-xs uppercase tracking-wider text-ivory-warm"><tr><th className="p-4">Technology</th><th className="p-4">Provider</th><th className="p-4">Purpose</th><th className="p-4">Category</th><th className="p-4">Duration</th><th className="p-4">First/Third Party</th><th className="p-4">Consent Required</th></tr></thead><tbody>{auditInventory.map(([technology, provider, purpose, category, duration, party, consent]) => <tr key={technology} className="border-t border-burgundy-deep/15 align-top"><th scope="row" className="p-4 font-semibold text-burgundy-deep">{technology}</th><td className="p-4 leading-relaxed">{provider}</td><td className="p-4 leading-relaxed">{purpose}</td><td className="p-4 leading-relaxed">{category}</td><td className="p-4 leading-relaxed">{duration}</td><td className="p-4 leading-relaxed">{party}</td><td className="p-4 leading-relaxed">{consent}</td></tr>)}</tbody></table></div></section>
          <section className="space-y-4"><h2 className={heading}>7. Strictly Necessary Technologies</h2><p className={text}>The website’s React application, local assets, server routes and security controls provide its core pages, forms and requests. These are not browser cookies. The anonymous first-load check found no cookie, so no strictly necessary cookie name or duration can be reported.</p></section>
          <section className="space-y-4"><h2 className={heading}>8. Functional Technologies</h2><p className={text}>No functional cookie or preference storage key was observed on an anonymous first load. Supabase Auth is configured to persist an authenticated session if one exists, but no anonymous session storage key was observed. This is browser storage capability, not a named cookie.</p></section>
          <section className="space-y-4"><h2 className={heading}>9. Analytics Technologies</h2><p className={text}>The audit found no Google Analytics, Google Tag Manager, Meta Pixel, TikTok Pixel, Google Ads conversion tag, Microsoft Clarity, Hotjar, LinkedIn Insight Tag or other analytics script in the source, configuration or dependencies.</p></section>
          <section className="space-y-4"><h2 className={heading}>10. Advertising and Marketing Technologies</h2><p className={text}>The audit found no advertising network, behavioural advertising script, marketing pixel or conversion-tracking technology. D’Fabulous does not describe advertising or marketing cookies as active.</p></section>
          <section className="space-y-4"><h2 className={heading}>11. Third-Party Technologies</h2><p className={text}>The page loads Google Fonts resources, and the application uses Supabase requests. The website also displays ordinary external links to WhatsApp, Facebook, Instagram and TikTok. Those links are not embedded trackers and do not place the destination’s cookies on this website merely because they are displayed. Following a link or using an external service may be subject to that provider’s own technologies and terms.</p></section>
          <section className="space-y-4"><h2 className={heading}>12. Browser Storage and Similar Technologies</h2><p className={text}>The source contains no application calls to <code>document.cookie</code>, <code>localStorage</code>, <code>sessionStorage</code> or IndexedDB. An anonymous first-load test returned no cookies and no local or session storage keys. Supabase Auth is configured for persisted sessions for authenticated administration; this may use browser storage if an authenticated session is created, but it is not a marketing tracker and no anonymous key was observed.</p></section>
          <section className="space-y-4"><h2 className={heading}>13. How Consent Works</h2><p className={text}>The current website has no cookie banner or preference centre because the audit found no optional cookie or tracking technology being activated. Visitors are not required to accept optional cookies to browse. If non-essential cookies or tracking are introduced, D’Fabulous will request valid prior consent where required by PECR, UK GDPR, the Data Protection Act 2018 or applicable EU/EEA ePrivacy and data-protection rules. Continuing to browse will not be treated as consent where prior consent is legally required.</p></section>
          <section className="space-y-4"><h2 className={heading}>14. Withdrawing or Changing Consent</h2><p className={text}>There is currently no optional-cookie consent to withdraw through the website. If a consent mechanism is introduced, it should allow visitors to accept optional technologies, reject them, manage preferences and withdraw consent later.</p></section>
          <section className="space-y-4"><h2 className={heading}>15. Browser Cookie Controls</h2><p className={text}>Visitors can inspect, block and delete cookies or stored site data through browser settings. Controls vary by browser. Refusing optional technologies should not prevent access to the core website unless a particular service technically requires them; disabling a strictly necessary technology may affect the function that depends on it.</p></section>
          <section className="space-y-4"><h2 className={heading}>16. Third-Party Privacy Information</h2><p className={text}>Independent providers control their own practices. Relevant information includes <a className="font-medium text-burgundy-rich underline underline-offset-4" href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google’s privacy information</a>, <a className="font-medium text-burgundy-rich underline underline-offset-4" href="https://www.whatsapp.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">WhatsApp’s privacy information</a>, <a className="font-medium text-burgundy-rich underline underline-offset-4" href="https://www.facebook.com/privacy/policies/" target="_blank" rel="noopener noreferrer">Facebook’s privacy information</a>, <a className="font-medium text-burgundy-rich underline underline-offset-4" href="https://privacycenter.instagram.com/policy/" target="_blank" rel="noopener noreferrer">Instagram’s privacy information</a> and <a className="font-medium text-burgundy-rich underline underline-offset-4" href="https://www.tiktok.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">TikTok’s privacy information</a>.</p></section>
          <section className="space-y-4"><h2 className={heading}>17. International Data Transfers</h2><p className={text}>Google Fonts, Supabase and external social or communication platforms may process request or account information outside the UK or EEA depending on their operation. Where applicable, D’Fabulous will use safeguards required by relevant law. No specific transfer mechanism is claimed here.</p></section>
          <section className="space-y-4"><h2 className={heading}>18. Data Retention</h2><p className={text}>No named cookie duration was identified because no named browser cookie was verified. Any future cookie must be assessed for its provider, purpose and duration before it is added to this policy. Enquiry, booking and account retention is addressed in the separate <a className="font-medium text-burgundy-rich underline underline-offset-4" href="/privacy">Privacy Policy</a>.</p></section>
          <section className="space-y-4"><h2 className={heading}>19. Security</h2><p className={text}>D’Fabulous uses reasonable technical and organisational measures for its website and related services. No policy guarantees complete security for online communications or independent third-party services. Do not send unnecessary sensitive information through external services.</p></section>
          <section className="space-y-4"><h2 className={heading}>20. Children’s Privacy</h2><p className={text}>This is a general business website and is not specifically directed at children. D’Fabulous does not knowingly use cookies or similar technologies to build behavioural profiles of children.</p></section>
          <section className="space-y-4"><h2 className={heading}>21. Changes to This Cookie Policy</h2><p className={text}>D’Fabulous may update this policy when its website, technology, services or legal requirements change. Significant changes will be reflected in a revised policy and date and, where reasonably appropriate, an on-site notice.</p></section>
          <section className="space-y-4"><h2 className={heading}>22. Contact Details</h2><p className={text}>Contact D’Fabulous about cookies, privacy or preferences using:</p><address className="not-italic leading-relaxed text-burgundy-deep"><strong>DFABULOUSS ENT LTD</strong><br />7 Bell Yard<br />London WC2A 2JR<br />United Kingdom<br />Company registration number: 12638479<br />VAT: Not VAT registered / N/A<br />Email: <a className="underline underline-offset-4" href="mailto:fabulousevents@hotmail.com">fabulousevents@hotmail.com</a><br />WhatsApp: use the official WhatsApp contact displayed on the website.</address></section>
          <section className="border-t border-burgundy-deep/15 pt-10 space-y-4"><h2 className={heading}>23. Effective Date and Last Updated</h2><p className={text}>Effective date: 2 September 2026.<br />Last updated: 2 September 2026.</p></section>
        </article>
      </Container>
    </main>
  </>
);